backend:
  name: git-gateway
  branch: main

media_folder: static/images/uploads
public_folder: /images/uploads

collections:
  - name: "pages"
    label: "Pages"
    folder: "src/content/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}
      - label: "Theme"
        name: "theme"
        widget: "object"
        fields:
          - {label: "Primary Color", name: "primary", widget: "color", required: false}
          - {label: "Secondary Color", name: "secondary", widget: "color", required: false}
      - label: "Blocks"
        name: "blocks"
        widget: "list"
        types:
          - label: "Hero"
            name: "hero"
            widget: "object"
            fields:
              - {label: "Logo", name: "logo", widget: "image"}
              - {label: "Image", name: "image", widget: "image"}
              - {label: "Background Image", name: "backgroundImage", widget: "image"}
              - {label: "Background Color", name: "backgroundColor", widget: "color"}
              - {label: "Description", name: "description", widget: "text"}
              - {label: "Call Action", name: "callAction", widget: "string"}
              - {label: "Call Action URL", name: "callActionURL", widget: "string"}
              - {label: "Call Action Text Color", name: "callActionTextColor", widget: "color", required: false}
          - label: "Title"
            name: "title"
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Subtitle", name: "subtitle", widget: "string", required: false}
          - label: "Content Box"
            name: "contentBox"
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: "string", required: false}
              - {label: "Big Title", name: "bigTitle", widget: "boolean", required: false}
              - {label: "Underline Title", name: "underline", widget: "boolean", required: false}
              - {label: "Body", name: "body", widget: "markdown"}
              - {label: "Call Action", name: "callAction", widget: "string", required: false}
              - {label: "Call Action URL", name: "callActionURL", widget: "string", required: false}
          - label: "Grid"
            name: "grid"
            widget: "object"
            fields:
              - {label: "Small Columns", name: "smCols", widget: "number", default: 1}
              - {label: "Large Columns", name: "lgCols", widget: "number", required: false}
              - label: "Elements"
                name: "elements"
                widget: "list"
                fields:
                   - {label: "Animated", name: "animated", widget: "boolean", default: true}
                   - {label: "Block", name: "block", widget: "object", fields: [{label: "Raw JSON Block", name: "raw", widget: "code"}]} 
          - label: "Image"
            name: "image"
            widget: "object"
            fields:
              - {label: "Source", name: "src", widget: "image"}
              - {label: "Link", name: "href", widget: "string", required: false}
